name: deploy to github page


on:
  #push:
  #  branches: [ master ]
  #workflow_run:
  #  workflows: ["schedule"]
  #  types:
  #    - completed
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cp -r api docs/public/
          cd docs
          yarn install
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build # The folder the action should deploy.
